### ISSUE TITLE
区域特征提取

### ISSUE THREAD

**Issue by HN123-123** [luo3300612/image-captioning-DLCT#24]
我尝试使用您的代码自己常见特征集，但是还有部分疑问。region_after和region_before 分别取自proposal_box_features和proposal_box_features1（均值），这有何区别？？
另外我去https://github.com/facebookresearch/grid-feats-vqa下也并未找到相应区域yaml文件，请问您是否可以分享下您的X-101-region.yaml和X-152-region.yaml文件？？

**Comment by HN123-123** [comment]
另外，我发现您提供的区域特征生成文件直接将特征保存为.hdf5文件形式，我如果想保存源形式的话应该怎么做呢？？

**Comment by luo3300612** [comment]
你好，这两者的区别是，before是roi pooling之后的特征，after是before再经过检测头的特征，我们用的模型是faster rcnn dc5，如果没有记错的话，after就是before经过fc之后的特征，在我们的实验中after的结果没有before好，所以我们用的就是before的特征

主要的数据都在[这三行](https://github.com/luo3300612/image-captioning-DLCT/blob/main/others/extract_region_feature.py#L185)，你把data=后面的tensor拿出来单独保存就行了

如果你想保存成npy的话，就把feature box size在一起保存成npz
如果你想保存成pth的话，可以弄一个字典用torch.save保存成pth

**Comment by Baixiaobai201619707** [comment]
@luo3300612 @HN123-123 你们好！我尝试使用others/extract_region_feature.py文件抽取coco_online_test2014数据集的特征，但是遇到下面的错误，请问你们知道怎么解决吗？
```
[06/16 14:17:39 fvcore.common.checkpoint]: [Checkpointer] Loading from others/X-101.pth ...
Traceback (most recent call last):
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/catalog.py", line 55, in get
    f = DatasetCatalog._REGISTERED[name]
KeyError: 'coco_2014_test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bwh/python/d_3_1/others/extract_region_feature.py", line 139, in <module>
    data_loader = build_detection_test_loader_with_attributes(cfg, dataset_name)
  File "/home/bwh/python/d_3_1/others/grid_feats/build_loader.py", line 88, in build_detection_test_loader_with_attributes
    else None,
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/build.py", line 224, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/bwh/anaconda3/envs/m2release/lib/python3.6/site-packages/detectron2/data/catalog.py", line 59, in get
    name, ", ".join(DatasetCatalog._REGISTERED.keys())
KeyError: "Dataset 'coco_2014_test' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, visual_genome_train, visual_genome_val, visual_genome_test"

```
